name: Test and lint

on: [push]

jobs:
  test:
    name: Run tests against SQLAlchemy 2
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]
      fail-fast: false

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          # We can't use `cache: poetry` here, due to
          # <https://github.com/actions/setup-python/issues/369>.
          cache: pip
          cache-dependency-path: "**/poetry.lock"
      - name: Install poetry
        run: pip --disable-pip-version-check install -U poetry
      - name: Install Python packages
        run: poetry install
      - name: Lint with flake8
        run: |
          poetry run flake8 --version
          poetry run flake8 --show-source --statistics sqla_utils test_sqla_utils
      - name: Type checking with mypy
        run: |
          poetry run mypy --version
          poetry run mypy sqla_utils test_sqla_utils
      - name: Test with pytest
        env:
          SQLALCHEMY_WARN_20: 1
        run: poetry run pytest

  test14:
    name: Run tests against SQLAlchemy 1.4
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]
      fail-fast: false

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          # We can't use `cache: poetry` here, due to
          # <https://github.com/actions/setup-python/issues/369>.
          cache: pip
          cache-dependency-path: "**/poetry.lock"
      - name: Install poetry
        run: pip --disable-pip-version-check install -U poetry
      - name: Install Python packages
        run: |
          poetry install
          poetry add SQLAlchemy==^1.4
      - name: Test with pytest
        env:
          SQLALCHEMY_WARN_20: 1
        run: poetry run pytest
